// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for CalendarTaskItemStatus.
const (
	CalendarTaskItemStatusCancelled CalendarTaskItemStatus = "cancelled"
	CalendarTaskItemStatusDone      CalendarTaskItemStatus = "done"
	CalendarTaskItemStatusPending   CalendarTaskItemStatus = "pending"
)

// Valid indicates whether the value is a known member of the CalendarTaskItemStatus enum.
func (e CalendarTaskItemStatus) Valid() bool {
	switch e {
	case CalendarTaskItemStatusCancelled:
		return true
	case CalendarTaskItemStatusDone:
		return true
	case CalendarTaskItemStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for RecurrenceRuleRequestFrequency.
const (
	RecurrenceRuleRequestFrequencyDaily   RecurrenceRuleRequestFrequency = "daily"
	RecurrenceRuleRequestFrequencyMonthly RecurrenceRuleRequestFrequency = "monthly"
	RecurrenceRuleRequestFrequencyWeekly  RecurrenceRuleRequestFrequency = "weekly"
)

// Valid indicates whether the value is a known member of the RecurrenceRuleRequestFrequency enum.
func (e RecurrenceRuleRequestFrequency) Valid() bool {
	switch e {
	case RecurrenceRuleRequestFrequencyDaily:
		return true
	case RecurrenceRuleRequestFrequencyMonthly:
		return true
	case RecurrenceRuleRequestFrequencyWeekly:
		return true
	default:
		return false
	}
}

// Defines values for RecurrenceRuleResponseFrequency.
const (
	RecurrenceRuleResponseFrequencyDaily   RecurrenceRuleResponseFrequency = "daily"
	RecurrenceRuleResponseFrequencyMonthly RecurrenceRuleResponseFrequency = "monthly"
	RecurrenceRuleResponseFrequencyWeekly  RecurrenceRuleResponseFrequency = "weekly"
)

// Valid indicates whether the value is a known member of the RecurrenceRuleResponseFrequency enum.
func (e RecurrenceRuleResponseFrequency) Valid() bool {
	switch e {
	case RecurrenceRuleResponseFrequencyDaily:
		return true
	case RecurrenceRuleResponseFrequencyMonthly:
		return true
	case RecurrenceRuleResponseFrequencyWeekly:
		return true
	default:
		return false
	}
}

// Defines values for TaskResponseStatus.
const (
	TaskResponseStatusCancelled TaskResponseStatus = "cancelled"
	TaskResponseStatusDone      TaskResponseStatus = "done"
	TaskResponseStatusPending   TaskResponseStatus = "pending"
)

// Valid indicates whether the value is a known member of the TaskResponseStatus enum.
func (e TaskResponseStatus) Valid() bool {
	switch e {
	case TaskResponseStatusCancelled:
		return true
	case TaskResponseStatusDone:
		return true
	case TaskResponseStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for GetTasksParamsStatus.
const (
	Pending   GetTasksParamsStatus = "pending"
	TodayDone GetTasksParamsStatus = "today_done"
)

// Valid indicates whether the value is a known member of the GetTasksParamsStatus enum.
func (e GetTasksParamsStatus) Valid() bool {
	switch e {
	case Pending:
		return true
	case TodayDone:
		return true
	default:
		return false
	}
}

// AppreciationResponse defines model for AppreciationResponse.
type AppreciationResponse struct {
	CreatedAt    *time.Time `json:"created_at,omitempty"`
	FromUserId   *int64     `json:"from_user_id,omitempty"`
	FromUserName *string    `json:"from_user_name,omitempty"`
	Id           *int64     `json:"id,omitempty"`
	Message      *string    `json:"message,omitempty"`
	TaskId       *int64     `json:"task_id,omitempty"`
	TaskTitle    *string    `json:"task_title,omitempty"`
	ToUserId     *int64     `json:"to_user_id,omitempty"`
	ToUserName   *string    `json:"to_user_name,omitempty"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken  *string       `json:"access_token,omitempty"`
	RefreshToken *string       `json:"refresh_token,omitempty"`
	User         *UserResponse `json:"user,omitempty"`
}

// CalendarDayItem defines model for CalendarDayItem.
type CalendarDayItem struct {
	Date  *openapi_types.Date `json:"date,omitempty"`
	Tasks *[]CalendarTaskItem `json:"tasks,omitempty"`
}

// CalendarTaskItem defines model for CalendarTaskItem.
type CalendarTaskItem struct {
	// AppreciatedByMe ログインユーザーが感謝スタンプを送信済みかどうか
	AppreciatedByMe *bool   `json:"appreciated_by_me,omitempty"`
	Category        *string `json:"category,omitempty"`

	// DoneByUserId 完了者のユーザーID（未完了は null）
	DoneByUserId *int64 `json:"done_by_user_id,omitempty"`

	// DoneByUserName 完了者の名前（未完了は null）
	DoneByUserName   *string                 `json:"done_by_user_name,omitempty"`
	RecurrenceRuleId *int64                  `json:"recurrence_rule_id,omitempty"`
	ScheduledDate    *openapi_types.Date     `json:"scheduled_date,omitempty"`
	Status           *CalendarTaskItemStatus `json:"status,omitempty"`

	// TaskId 実体化済みタスクの ID（まだ完了・作成されていない仮想インスタンスは null）
	TaskId   *int64  `json:"task_id,omitempty"`
	Title    *string `json:"title,omitempty"`
	UserId   *int64  `json:"user_id,omitempty"`
	UserName *string `json:"user_name,omitempty"`
}

// CalendarTaskItemStatus defines model for CalendarTaskItem.Status.
type CalendarTaskItemStatus string

// ContributionItem defines model for ContributionItem.
type ContributionItem struct {
	Category *string `json:"category,omitempty"`
	Count    *int    `json:"count,omitempty"`
	UserId   *int64  `json:"user_id,omitempty"`
	UserName *string `json:"user_name,omitempty"`
}

// CreateFamilyGoalRequest defines model for CreateFamilyGoalRequest.
type CreateFamilyGoalRequest struct {
	TargetPoints int    `json:"target_points"`
	Title        string `json:"title"`
}

// CreateFamilyRequest defines model for CreateFamilyRequest.
type CreateFamilyRequest struct {
	Name string `json:"name"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Category *string `json:"category,omitempty"`

	// RecurrenceRuleId 繰り返しルールから生成されたインスタンスの場合に設定
	RecurrenceRuleId *int64 `json:"recurrence_rule_id,omitempty"`

	// ScheduledDate 予定日（繰り返しタスクのインスタンス化日）
	ScheduledDate *openapi_types.Date `json:"scheduled_date,omitempty"`
	Title         string              `json:"title"`
}

// FamilyGoalResponse defines model for FamilyGoalResponse.
type FamilyGoalResponse struct {
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	CurrentPoints *int       `json:"current_points,omitempty"`
	Id            *int64     `json:"id,omitempty"`
	TargetPoints  *int       `json:"target_points,omitempty"`
	Title         *string    `json:"title,omitempty"`
}

// FamilyResponse defines model for FamilyResponse.
type FamilyResponse struct {
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	Id         *int64     `json:"id,omitempty"`
	InviteCode *string    `json:"invite_code,omitempty"`
	Name       *string    `json:"name,omitempty"`
}

// JoinFamilyRequest defines model for JoinFamilyRequest.
type JoinFamilyRequest struct {
	InviteCode string `json:"invite_code"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RecurrenceRuleRequest defines model for RecurrenceRuleRequest.
type RecurrenceRuleRequest struct {
	Category *string `json:"category,omitempty"`

	// DayOfMonth 1〜31（monthly 日付指定のみ）
	DayOfMonth *int `json:"day_of_month,omitempty"`

	// DayOfWeek 0=日〜6=土（weekly のみ）
	DayOfWeek *int                           `json:"day_of_week,omitempty"`
	EndDate   *openapi_types.Date            `json:"end_date,omitempty"`
	Frequency RecurrenceRuleRequestFrequency `json:"frequency"`
	StartDate openapi_types.Date             `json:"start_date"`
	Title     string                         `json:"title"`

	// WeekOfMonth 第N週（1〜5、monthly 曜日指定時）
	WeekOfMonth *int `json:"week_of_month,omitempty"`
}

// RecurrenceRuleRequestFrequency defines model for RecurrenceRuleRequest.Frequency.
type RecurrenceRuleRequestFrequency string

// RecurrenceRuleResponse defines model for RecurrenceRuleResponse.
type RecurrenceRuleResponse struct {
	Category   *string                          `json:"category,omitempty"`
	CreatedAt  *time.Time                       `json:"created_at,omitempty"`
	CreatedBy  *int64                           `json:"created_by,omitempty"`
	DayOfMonth *int                             `json:"day_of_month,omitempty"`
	DayOfWeek  *int                             `json:"day_of_week,omitempty"`
	EndDate    *openapi_types.Date              `json:"end_date,omitempty"`
	FamilyId   *int64                           `json:"family_id,omitempty"`
	Frequency  *RecurrenceRuleResponseFrequency `json:"frequency,omitempty"`
	Id         *int64                           `json:"id,omitempty"`
	StartDate  *openapi_types.Date              `json:"start_date,omitempty"`
	Title      *string                          `json:"title,omitempty"`

	// WeekOfMonth 第N週（1〜5）
	WeekOfMonth *int `json:"week_of_month,omitempty"`
}

// RecurrenceRuleResponseFrequency defines model for RecurrenceRuleResponse.Frequency.
type RecurrenceRuleResponseFrequency string

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
	Role     string              `json:"role"`
}

// SendAppreciationRequest defines model for SendAppreciationRequest.
type SendAppreciationRequest struct {
	Message string `json:"message"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	Category         *string                 `json:"category,omitempty"`
	Comments         *[]AppreciationResponse `json:"comments,omitempty"`
	CreatedAt        *time.Time              `json:"created_at,omitempty"`
	CreatedBy        *int64                  `json:"created_by,omitempty"`
	DoneAt           *time.Time              `json:"done_at,omitempty"`
	DoneBy           *int64                  `json:"done_by,omitempty"`
	FamilyId         *int64                  `json:"family_id,omitempty"`
	Id               *int64                  `json:"id,omitempty"`
	RecurrenceRuleId *int64                  `json:"recurrence_rule_id,omitempty"`
	ScheduledDate    *openapi_types.Date     `json:"scheduled_date,omitempty"`
	Status           *TaskResponseStatus     `json:"status,omitempty"`
	Title            *string                 `json:"title,omitempty"`
}

// TaskResponseStatus defines model for TaskResponse.Status.
type TaskResponseStatus string

// TaskTemplateResponse defines model for TaskTemplateResponse.
type TaskTemplateResponse struct {
	Category *string `json:"category,omitempty"`
	Id       *int64  `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken  *string `json:"access_token,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	IconUrl *string `json:"icon_url,omitempty"`
	Name    *string `json:"name,omitempty"`
	Role    *string `json:"role,omitempty"`
}

// UpdateTaskRequest defines model for UpdateTaskRequest.
type UpdateTaskRequest struct {
	Category *string `json:"category,omitempty"`
	Title    string  `json:"title"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	Email      *string    `json:"email,omitempty"`
	EnmanPoint *int       `json:"enman_point,omitempty"`
	FamilyId   *int64     `json:"family_id,omitempty"`
	IconUrl    *string    `json:"icon_url,omitempty"`
	Id         *int64     `json:"id,omitempty"`
	InviteCode *string    `json:"invite_code,omitempty"`
	Name       *string    `json:"name,omitempty"`
	Role       *string    `json:"role,omitempty"`
}

// GetHealth200Response defines model for getHealth_200_response.
type GetHealth200Response struct {
	Status *string `json:"status,omitempty"`
}

// GetHealthDefaultResponse defines model for getHealth_default_response.
type GetHealthDefaultResponse struct {
	ErrorMessages *[]string `json:"errorMessages,omitempty"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// GetCalendarParams defines parameters for GetCalendar.
type GetCalendarParams struct {
	Year  int `form:"year" json:"year"`
	Month int `form:"month" json:"month"`
}

// GetTasksParams defines parameters for GetTasks.
type GetTasksParams struct {
	// Status pending: これからやること / today_done: 今日終わったこと
	Status *GetTasksParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetTasksParamsStatus defines parameters for GetTasks.
type GetTasksParamsStatus string

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// DeleteAuthLogoutJSONRequestBody defines body for DeleteAuthLogout for application/json ContentType.
type DeleteAuthLogoutJSONRequestBody = LogoutRequest

// PostAuthRefreshJSONRequestBody defines body for PostAuthRefresh for application/json ContentType.
type PostAuthRefreshJSONRequestBody = RefreshRequest

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = RegisterRequest

// PostFamiliesJSONRequestBody defines body for PostFamilies for application/json ContentType.
type PostFamiliesJSONRequestBody = CreateFamilyRequest

// PostFamiliesGoalsJSONRequestBody defines body for PostFamiliesGoals for application/json ContentType.
type PostFamiliesGoalsJSONRequestBody = CreateFamilyGoalRequest

// PostFamiliesJoinJSONRequestBody defines body for PostFamiliesJoin for application/json ContentType.
type PostFamiliesJoinJSONRequestBody = JoinFamilyRequest

// PostRecurrenceRulesJSONRequestBody defines body for PostRecurrenceRules for application/json ContentType.
type PostRecurrenceRulesJSONRequestBody = RecurrenceRuleRequest

// PatchRecurrenceRulesJSONRequestBody defines body for PatchRecurrenceRules for application/json ContentType.
type PatchRecurrenceRulesJSONRequestBody = RecurrenceRuleRequest

// PostTasksJSONRequestBody defines body for PostTasks for application/json ContentType.
type PostTasksJSONRequestBody = CreateTaskRequest

// PatchTaskJSONRequestBody defines body for PatchTask for application/json ContentType.
type PatchTaskJSONRequestBody = UpdateTaskRequest

// PostTasksAppreciationJSONRequestBody defines body for PostTasksAppreciation for application/json ContentType.
type PostTasksAppreciationJSONRequestBody = SendAppreciationRequest

// PatchUsersMeJSONRequestBody defines body for PatchUsersMe for application/json ContentType.
type PatchUsersMeJSONRequestBody = UpdateProfileRequest
