// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for TaskResponseStatus.
const (
	TaskResponseStatusDone    TaskResponseStatus = "done"
	TaskResponseStatusPending TaskResponseStatus = "pending"
)

// Valid indicates whether the value is a known member of the TaskResponseStatus enum.
func (e TaskResponseStatus) Valid() bool {
	switch e {
	case TaskResponseStatusDone:
		return true
	case TaskResponseStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for GetTasksParamsStatus.
const (
	GetTasksParamsStatusPending   GetTasksParamsStatus = "pending"
	GetTasksParamsStatusTodayDone GetTasksParamsStatus = "today_done"
)

// Valid indicates whether the value is a known member of the GetTasksParamsStatus enum.
func (e GetTasksParamsStatus) Valid() bool {
	switch e {
	case GetTasksParamsStatusPending:
		return true
	case GetTasksParamsStatusTodayDone:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken  *string       `json:"access_token,omitempty"`
	RefreshToken *string       `json:"refresh_token,omitempty"`
	User         *UserResponse `json:"user,omitempty"`
}

// CreateFamilyRequest defines model for CreateFamilyRequest.
type CreateFamilyRequest struct {
	Name string `json:"name"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Category *string `json:"category,omitempty"`
	Title    string  `json:"title"`
}

// FamilyResponse defines model for FamilyResponse.
type FamilyResponse struct {
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	Id         *int64     `json:"id,omitempty"`
	InviteCode *string    `json:"invite_code,omitempty"`
	Name       *string    `json:"name,omitempty"`
}

// JoinFamilyRequest defines model for JoinFamilyRequest.
type JoinFamilyRequest struct {
	InviteCode string `json:"invite_code"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
	Role     string              `json:"role"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	Category  *string             `json:"category,omitempty"`
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	CreatedBy *int64              `json:"created_by,omitempty"`
	DoneAt    *time.Time          `json:"done_at,omitempty"`
	DoneBy    *int64              `json:"done_by,omitempty"`
	FamilyId  *int64              `json:"family_id,omitempty"`
	Id        *int64              `json:"id,omitempty"`
	Status    *TaskResponseStatus `json:"status,omitempty"`
	Title     *string             `json:"title,omitempty"`
}

// TaskResponseStatus defines model for TaskResponse.Status.
type TaskResponseStatus string

// TaskTemplateResponse defines model for TaskTemplateResponse.
type TaskTemplateResponse struct {
	Category *string `json:"category,omitempty"`
	Id       *int64  `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken  *string `json:"access_token,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	IconUrl *string `json:"icon_url,omitempty"`
	Name    *string `json:"name,omitempty"`
	Role    *string `json:"role,omitempty"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	Email      *string    `json:"email,omitempty"`
	EnmanPoint *int       `json:"enman_point,omitempty"`
	FamilyId   *int64     `json:"family_id,omitempty"`
	IconUrl    *string    `json:"icon_url,omitempty"`
	Id         *int64     `json:"id,omitempty"`
	Name       *string    `json:"name,omitempty"`
	Role       *string    `json:"role,omitempty"`
}

// GetHealth200Response defines model for getHealth_200_response.
type GetHealth200Response struct {
	Status *string `json:"status,omitempty"`
}

// GetHealthDefaultResponse defines model for getHealth_default_response.
type GetHealthDefaultResponse struct {
	ErrorMessages *[]string `json:"errorMessages,omitempty"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// GetTasksParams defines parameters for GetTasks.
type GetTasksParams struct {
	// Status pending: これからやること / today_done: 今日終わったこと
	Status *GetTasksParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetTasksParamsStatus defines parameters for GetTasks.
type GetTasksParamsStatus string

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// DeleteAuthLogoutJSONRequestBody defines body for DeleteAuthLogout for application/json ContentType.
type DeleteAuthLogoutJSONRequestBody = LogoutRequest

// PostAuthRefreshJSONRequestBody defines body for PostAuthRefresh for application/json ContentType.
type PostAuthRefreshJSONRequestBody = RefreshRequest

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = RegisterRequest

// PostFamiliesJSONRequestBody defines body for PostFamilies for application/json ContentType.
type PostFamiliesJSONRequestBody = CreateFamilyRequest

// PostFamiliesJoinJSONRequestBody defines body for PostFamiliesJoin for application/json ContentType.
type PostFamiliesJoinJSONRequestBody = JoinFamilyRequest

// PostTasksJSONRequestBody defines body for PostTasks for application/json ContentType.
type PostTasksJSONRequestBody = CreateTaskRequest

// PatchUsersMeJSONRequestBody defines body for PatchUsersMe for application/json ContentType.
type PatchUsersMeJSONRequestBody = UpdateProfileRequest
