// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

// GetHealth200Response defines model for getHealth_200_response.
type GetHealth200Response struct {
	Status *string `json:"status,omitempty"`
}

// GetHealthDefaultResponse defines model for getHealth_default_response.
type GetHealthDefaultResponse struct {
	ErrorMessages *[]string `json:"errorMessages,omitempty"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string
