// Code generated by auth_generator.go DO NOT EDIT.
// Source: api/resolved/openapi/openapi.yaml
// Run "make gen" to regenerate.
package openapi

// bearerAuthRoutes は Bearer JWT 認証が必要なルートの集合です。
// キー形式: "METHOD /echo/path/pattern"
var bearerAuthRoutes = map[string]struct{}{
	"DELETE /auth/logout": {},
	"GET /calendar": {},
	"POST /families": {},
	"GET /families/goals": {},
	"POST /families/goals": {},
	"POST /families/join": {},
	"GET /family/timeline": {},
	"GET /notifications": {},
	"GET /recurrence-rules": {},
	"POST /recurrence-rules": {},
	"DELETE /recurrence-rules/:ruleId": {},
	"PATCH /recurrence-rules/:ruleId": {},
	"GET /stats/contributions": {},
	"GET /task-templates": {},
	"GET /tasks": {},
	"POST /tasks": {},
	"DELETE /tasks/:taskId": {},
	"PATCH /tasks/:taskId": {},
	"POST /tasks/:taskId/appreciations": {},
	"PATCH /tasks/:taskId/cancel": {},
	"PATCH /tasks/:taskId/done": {},
	"GET /users/me": {},
	"PATCH /users/me": {},
}

// RequiresBearerAuth は指定の HTTP メソッドと Echo ルートパターンが
// Bearer JWT 認証を必要とするかどうかを返します。
// middleware.JWTAuthMiddleware から呼び出されます。
func RequiresBearerAuth(method, echoPath string) bool {
	_, ok := bearerAuthRoutes[method+" "+echoPath]
	return ok
}
