// Code generated by auth_generator.go DO NOT EDIT.
// Source: api/resolved/openapi/openapi.yaml
// Run "make gen" to regenerate.
package openapi

// bearerAuthRoutes は Bearer JWT 認証が必要なルートの集合です。
// キー形式: "METHOD /echo/path/pattern"
var bearerAuthRoutes = map[string]struct{}{
	"DELETE /auth/logout": {},
	"POST /families": {},
	"POST /families/join": {},
	"GET /users/me": {},
	"PATCH /users/me": {},
}

// RequiresBearerAuth は指定の HTTP メソッドと Echo ルートパターンが
// Bearer JWT 認証を必要とするかどうかを返します。
// middleware.JWTAuthMiddleware から呼び出されます。
func RequiresBearerAuth(method, echoPath string) bool {
	_, ok := bearerAuthRoutes[method+" "+echoPath]
	return ok
}
