// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/cancel_task.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/cancel_task.go -destination=internal/usecase/mock/cancel_task.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockCancelTaskInputPort is a mock of CancelTaskInputPort interface.
type MockCancelTaskInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockCancelTaskInputPortMockRecorder
	isgomock struct{}
}

// MockCancelTaskInputPortMockRecorder is the mock recorder for MockCancelTaskInputPort.
type MockCancelTaskInputPortMockRecorder struct {
	mock *MockCancelTaskInputPort
}

// NewMockCancelTaskInputPort creates a new mock instance.
func NewMockCancelTaskInputPort(ctrl *gomock.Controller) *MockCancelTaskInputPort {
	mock := &MockCancelTaskInputPort{ctrl: ctrl}
	mock.recorder = &MockCancelTaskInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCancelTaskInputPort) EXPECT() *MockCancelTaskInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCancelTaskInputPort) Execute(ctx context.Context, input usecase.CancelTaskInput) (*usecase.CancelTaskOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.CancelTaskOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCancelTaskInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCancelTaskInputPort)(nil).Execute), ctx, input)
}
