// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/complete_task.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/complete_task.go -destination=internal/usecase/mock/complete_task.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockCompleteTaskInputPort is a mock of CompleteTaskInputPort interface.
type MockCompleteTaskInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockCompleteTaskInputPortMockRecorder
	isgomock struct{}
}

// MockCompleteTaskInputPortMockRecorder is the mock recorder for MockCompleteTaskInputPort.
type MockCompleteTaskInputPortMockRecorder struct {
	mock *MockCompleteTaskInputPort
}

// NewMockCompleteTaskInputPort creates a new mock instance.
func NewMockCompleteTaskInputPort(ctrl *gomock.Controller) *MockCompleteTaskInputPort {
	mock := &MockCompleteTaskInputPort{ctrl: ctrl}
	mock.recorder = &MockCompleteTaskInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompleteTaskInputPort) EXPECT() *MockCompleteTaskInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCompleteTaskInputPort) Execute(ctx context.Context, input usecase.CompleteTaskInput) (*usecase.CompleteTaskOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.CompleteTaskOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCompleteTaskInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCompleteTaskInputPort)(nil).Execute), ctx, input)
}
