// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/create_recurrence_rule.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/create_recurrence_rule.go -destination=internal/usecase/mock/create_recurrence_rule.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateRecurrenceRuleInputPort is a mock of CreateRecurrenceRuleInputPort interface.
type MockCreateRecurrenceRuleInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockCreateRecurrenceRuleInputPortMockRecorder
	isgomock struct{}
}

// MockCreateRecurrenceRuleInputPortMockRecorder is the mock recorder for MockCreateRecurrenceRuleInputPort.
type MockCreateRecurrenceRuleInputPortMockRecorder struct {
	mock *MockCreateRecurrenceRuleInputPort
}

// NewMockCreateRecurrenceRuleInputPort creates a new mock instance.
func NewMockCreateRecurrenceRuleInputPort(ctrl *gomock.Controller) *MockCreateRecurrenceRuleInputPort {
	mock := &MockCreateRecurrenceRuleInputPort{ctrl: ctrl}
	mock.recorder = &MockCreateRecurrenceRuleInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateRecurrenceRuleInputPort) EXPECT() *MockCreateRecurrenceRuleInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateRecurrenceRuleInputPort) Execute(ctx context.Context, input usecase.CreateRecurrenceRuleInput) (*usecase.CreateRecurrenceRuleOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.CreateRecurrenceRuleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateRecurrenceRuleInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateRecurrenceRuleInputPort)(nil).Execute), ctx, input)
}
