// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/create_family.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/create_family.go -destination=internal/usecase/mock/create_family.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateFamilyInputPort is a mock of CreateFamilyInputPort interface.
type MockCreateFamilyInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockCreateFamilyInputPortMockRecorder
	isgomock struct{}
}

// MockCreateFamilyInputPortMockRecorder is the mock recorder for MockCreateFamilyInputPort.
type MockCreateFamilyInputPortMockRecorder struct {
	mock *MockCreateFamilyInputPort
}

// NewMockCreateFamilyInputPort creates a new mock instance.
func NewMockCreateFamilyInputPort(ctrl *gomock.Controller) *MockCreateFamilyInputPort {
	mock := &MockCreateFamilyInputPort{ctrl: ctrl}
	mock.recorder = &MockCreateFamilyInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateFamilyInputPort) EXPECT() *MockCreateFamilyInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateFamilyInputPort) Execute(ctx context.Context, input usecase.CreateFamilyInput) (*usecase.CreateFamilyOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.CreateFamilyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateFamilyInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateFamilyInputPort)(nil).Execute), ctx, input)
}
