// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/create_task.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/create_task.go -destination=internal/usecase/mock/create_task.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateTaskInputPort is a mock of CreateTaskInputPort interface.
type MockCreateTaskInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockCreateTaskInputPortMockRecorder
	isgomock struct{}
}

// MockCreateTaskInputPortMockRecorder is the mock recorder for MockCreateTaskInputPort.
type MockCreateTaskInputPortMockRecorder struct {
	mock *MockCreateTaskInputPort
}

// NewMockCreateTaskInputPort creates a new mock instance.
func NewMockCreateTaskInputPort(ctrl *gomock.Controller) *MockCreateTaskInputPort {
	mock := &MockCreateTaskInputPort{ctrl: ctrl}
	mock.recorder = &MockCreateTaskInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateTaskInputPort) EXPECT() *MockCreateTaskInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateTaskInputPort) Execute(ctx context.Context, input usecase.CreateTaskInput) (*usecase.CreateTaskOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.CreateTaskOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateTaskInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateTaskInputPort)(nil).Execute), ctx, input)
}
