// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/create_family_goal.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/create_family_goal.go -destination=internal/usecase/mock/create_family_goal.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateFamilyGoalInputPort is a mock of CreateFamilyGoalInputPort interface.
type MockCreateFamilyGoalInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockCreateFamilyGoalInputPortMockRecorder
	isgomock struct{}
}

// MockCreateFamilyGoalInputPortMockRecorder is the mock recorder for MockCreateFamilyGoalInputPort.
type MockCreateFamilyGoalInputPortMockRecorder struct {
	mock *MockCreateFamilyGoalInputPort
}

// NewMockCreateFamilyGoalInputPort creates a new mock instance.
func NewMockCreateFamilyGoalInputPort(ctrl *gomock.Controller) *MockCreateFamilyGoalInputPort {
	mock := &MockCreateFamilyGoalInputPort{ctrl: ctrl}
	mock.recorder = &MockCreateFamilyGoalInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateFamilyGoalInputPort) EXPECT() *MockCreateFamilyGoalInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateFamilyGoalInputPort) Execute(ctx context.Context, input usecase.CreateFamilyGoalInput) (*usecase.CreateFamilyGoalOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.CreateFamilyGoalOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateFamilyGoalInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateFamilyGoalInputPort)(nil).Execute), ctx, input)
}
