// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/delete_recurrence_rule.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/delete_recurrence_rule.go -destination=internal/usecase/mock/delete_recurrence_rule.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockDeleteRecurrenceRuleInputPort is a mock of DeleteRecurrenceRuleInputPort interface.
type MockDeleteRecurrenceRuleInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteRecurrenceRuleInputPortMockRecorder
	isgomock struct{}
}

// MockDeleteRecurrenceRuleInputPortMockRecorder is the mock recorder for MockDeleteRecurrenceRuleInputPort.
type MockDeleteRecurrenceRuleInputPortMockRecorder struct {
	mock *MockDeleteRecurrenceRuleInputPort
}

// NewMockDeleteRecurrenceRuleInputPort creates a new mock instance.
func NewMockDeleteRecurrenceRuleInputPort(ctrl *gomock.Controller) *MockDeleteRecurrenceRuleInputPort {
	mock := &MockDeleteRecurrenceRuleInputPort{ctrl: ctrl}
	mock.recorder = &MockDeleteRecurrenceRuleInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteRecurrenceRuleInputPort) EXPECT() *MockDeleteRecurrenceRuleInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteRecurrenceRuleInputPort) Execute(ctx context.Context, input usecase.DeleteRecurrenceRuleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteRecurrenceRuleInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteRecurrenceRuleInputPort)(nil).Execute), ctx, input)
}
