// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/delete_task.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/delete_task.go -destination=internal/usecase/mock/delete_task.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockDeleteTaskInputPort is a mock of DeleteTaskInputPort interface.
type MockDeleteTaskInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteTaskInputPortMockRecorder
	isgomock struct{}
}

// MockDeleteTaskInputPortMockRecorder is the mock recorder for MockDeleteTaskInputPort.
type MockDeleteTaskInputPortMockRecorder struct {
	mock *MockDeleteTaskInputPort
}

// NewMockDeleteTaskInputPort creates a new mock instance.
func NewMockDeleteTaskInputPort(ctrl *gomock.Controller) *MockDeleteTaskInputPort {
	mock := &MockDeleteTaskInputPort{ctrl: ctrl}
	mock.recorder = &MockDeleteTaskInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteTaskInputPort) EXPECT() *MockDeleteTaskInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteTaskInputPort) Execute(ctx context.Context, input usecase.DeleteTaskInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteTaskInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteTaskInputPort)(nil).Execute), ctx, input)
}
