// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_family_timeline.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_family_timeline.go -destination=internal/usecase/mock/get_family_timeline.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGetFamilyTimelineInputPort is a mock of GetFamilyTimelineInputPort interface.
type MockGetFamilyTimelineInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetFamilyTimelineInputPortMockRecorder
	isgomock struct{}
}

// MockGetFamilyTimelineInputPortMockRecorder is the mock recorder for MockGetFamilyTimelineInputPort.
type MockGetFamilyTimelineInputPortMockRecorder struct {
	mock *MockGetFamilyTimelineInputPort
}

// NewMockGetFamilyTimelineInputPort creates a new mock instance.
func NewMockGetFamilyTimelineInputPort(ctrl *gomock.Controller) *MockGetFamilyTimelineInputPort {
	mock := &MockGetFamilyTimelineInputPort{ctrl: ctrl}
	mock.recorder = &MockGetFamilyTimelineInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetFamilyTimelineInputPort) EXPECT() *MockGetFamilyTimelineInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetFamilyTimelineInputPort) Execute(ctx context.Context, input usecase.GetFamilyTimelineInput) (*usecase.GetFamilyTimelineOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.GetFamilyTimelineOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetFamilyTimelineInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetFamilyTimelineInputPort)(nil).Execute), ctx, input)
}
