// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_current_user.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_current_user.go -destination=internal/usecase/mock/get_current_user.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGetCurrentUserInputPort is a mock of GetCurrentUserInputPort interface.
type MockGetCurrentUserInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetCurrentUserInputPortMockRecorder
	isgomock struct{}
}

// MockGetCurrentUserInputPortMockRecorder is the mock recorder for MockGetCurrentUserInputPort.
type MockGetCurrentUserInputPortMockRecorder struct {
	mock *MockGetCurrentUserInputPort
}

// NewMockGetCurrentUserInputPort creates a new mock instance.
func NewMockGetCurrentUserInputPort(ctrl *gomock.Controller) *MockGetCurrentUserInputPort {
	mock := &MockGetCurrentUserInputPort{ctrl: ctrl}
	mock.recorder = &MockGetCurrentUserInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetCurrentUserInputPort) EXPECT() *MockGetCurrentUserInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetCurrentUserInputPort) Execute(ctx context.Context, input usecase.GetCurrentUserInput) (*usecase.GetCurrentUserOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.GetCurrentUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetCurrentUserInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetCurrentUserInputPort)(nil).Execute), ctx, input)
}
