// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_contributions.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_contributions.go -destination=internal/usecase/mock/get_contributions.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGetContributionsInputPort is a mock of GetContributionsInputPort interface.
type MockGetContributionsInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetContributionsInputPortMockRecorder
	isgomock struct{}
}

// MockGetContributionsInputPortMockRecorder is the mock recorder for MockGetContributionsInputPort.
type MockGetContributionsInputPortMockRecorder struct {
	mock *MockGetContributionsInputPort
}

// NewMockGetContributionsInputPort creates a new mock instance.
func NewMockGetContributionsInputPort(ctrl *gomock.Controller) *MockGetContributionsInputPort {
	mock := &MockGetContributionsInputPort{ctrl: ctrl}
	mock.recorder = &MockGetContributionsInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetContributionsInputPort) EXPECT() *MockGetContributionsInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetContributionsInputPort) Execute(ctx context.Context, input usecase.GetContributionsInput) (*usecase.GetContributionsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.GetContributionsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetContributionsInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetContributionsInputPort)(nil).Execute), ctx, input)
}
