// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_calendar.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_calendar.go -destination=internal/usecase/mock/get_calendar.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGetCalendarInputPort is a mock of GetCalendarInputPort interface.
type MockGetCalendarInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetCalendarInputPortMockRecorder
	isgomock struct{}
}

// MockGetCalendarInputPortMockRecorder is the mock recorder for MockGetCalendarInputPort.
type MockGetCalendarInputPortMockRecorder struct {
	mock *MockGetCalendarInputPort
}

// NewMockGetCalendarInputPort creates a new mock instance.
func NewMockGetCalendarInputPort(ctrl *gomock.Controller) *MockGetCalendarInputPort {
	mock := &MockGetCalendarInputPort{ctrl: ctrl}
	mock.recorder = &MockGetCalendarInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetCalendarInputPort) EXPECT() *MockGetCalendarInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetCalendarInputPort) Execute(ctx context.Context, input usecase.GetCalendarInput) (*usecase.GetCalendarOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.GetCalendarOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetCalendarInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetCalendarInputPort)(nil).Execute), ctx, input)
}
