// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/join_family.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/join_family.go -destination=internal/usecase/mock/join_family.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockJoinFamilyInputPort is a mock of JoinFamilyInputPort interface.
type MockJoinFamilyInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockJoinFamilyInputPortMockRecorder
	isgomock struct{}
}

// MockJoinFamilyInputPortMockRecorder is the mock recorder for MockJoinFamilyInputPort.
type MockJoinFamilyInputPortMockRecorder struct {
	mock *MockJoinFamilyInputPort
}

// NewMockJoinFamilyInputPort creates a new mock instance.
func NewMockJoinFamilyInputPort(ctrl *gomock.Controller) *MockJoinFamilyInputPort {
	mock := &MockJoinFamilyInputPort{ctrl: ctrl}
	mock.recorder = &MockJoinFamilyInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJoinFamilyInputPort) EXPECT() *MockJoinFamilyInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockJoinFamilyInputPort) Execute(ctx context.Context, input usecase.JoinFamilyInput) (*usecase.JoinFamilyOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.JoinFamilyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockJoinFamilyInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockJoinFamilyInputPort)(nil).Execute), ctx, input)
}
