// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/list_task_templates.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/list_task_templates.go -destination=internal/usecase/mock/list_task_templates.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockListTaskTemplatesInputPort is a mock of ListTaskTemplatesInputPort interface.
type MockListTaskTemplatesInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockListTaskTemplatesInputPortMockRecorder
	isgomock struct{}
}

// MockListTaskTemplatesInputPortMockRecorder is the mock recorder for MockListTaskTemplatesInputPort.
type MockListTaskTemplatesInputPortMockRecorder struct {
	mock *MockListTaskTemplatesInputPort
}

// NewMockListTaskTemplatesInputPort creates a new mock instance.
func NewMockListTaskTemplatesInputPort(ctrl *gomock.Controller) *MockListTaskTemplatesInputPort {
	mock := &MockListTaskTemplatesInputPort{ctrl: ctrl}
	mock.recorder = &MockListTaskTemplatesInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListTaskTemplatesInputPort) EXPECT() *MockListTaskTemplatesInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListTaskTemplatesInputPort) Execute(ctx context.Context) (*usecase.ListTaskTemplatesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].(*usecase.ListTaskTemplatesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListTaskTemplatesInputPortMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListTaskTemplatesInputPort)(nil).Execute), ctx)
}
