// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/list_notifications.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/list_notifications.go -destination=internal/usecase/mock/list_notifications.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockListNotificationsInputPort is a mock of ListNotificationsInputPort interface.
type MockListNotificationsInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockListNotificationsInputPortMockRecorder
	isgomock struct{}
}

// MockListNotificationsInputPortMockRecorder is the mock recorder for MockListNotificationsInputPort.
type MockListNotificationsInputPortMockRecorder struct {
	mock *MockListNotificationsInputPort
}

// NewMockListNotificationsInputPort creates a new mock instance.
func NewMockListNotificationsInputPort(ctrl *gomock.Controller) *MockListNotificationsInputPort {
	mock := &MockListNotificationsInputPort{ctrl: ctrl}
	mock.recorder = &MockListNotificationsInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListNotificationsInputPort) EXPECT() *MockListNotificationsInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListNotificationsInputPort) Execute(ctx context.Context, input usecase.ListNotificationsInput) (*usecase.ListNotificationsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.ListNotificationsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListNotificationsInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListNotificationsInputPort)(nil).Execute), ctx, input)
}
