// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/list_recurrence_rules.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/list_recurrence_rules.go -destination=internal/usecase/mock/list_recurrence_rules.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockListRecurrenceRulesInputPort is a mock of ListRecurrenceRulesInputPort interface.
type MockListRecurrenceRulesInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockListRecurrenceRulesInputPortMockRecorder
	isgomock struct{}
}

// MockListRecurrenceRulesInputPortMockRecorder is the mock recorder for MockListRecurrenceRulesInputPort.
type MockListRecurrenceRulesInputPortMockRecorder struct {
	mock *MockListRecurrenceRulesInputPort
}

// NewMockListRecurrenceRulesInputPort creates a new mock instance.
func NewMockListRecurrenceRulesInputPort(ctrl *gomock.Controller) *MockListRecurrenceRulesInputPort {
	mock := &MockListRecurrenceRulesInputPort{ctrl: ctrl}
	mock.recorder = &MockListRecurrenceRulesInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListRecurrenceRulesInputPort) EXPECT() *MockListRecurrenceRulesInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListRecurrenceRulesInputPort) Execute(ctx context.Context, input usecase.ListRecurrenceRulesInput) (*usecase.ListRecurrenceRulesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.ListRecurrenceRulesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListRecurrenceRulesInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListRecurrenceRulesInputPort)(nil).Execute), ctx, input)
}
