// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/list_family_goals.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/list_family_goals.go -destination=internal/usecase/mock/list_family_goals.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockListFamilyGoalsInputPort is a mock of ListFamilyGoalsInputPort interface.
type MockListFamilyGoalsInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockListFamilyGoalsInputPortMockRecorder
	isgomock struct{}
}

// MockListFamilyGoalsInputPortMockRecorder is the mock recorder for MockListFamilyGoalsInputPort.
type MockListFamilyGoalsInputPortMockRecorder struct {
	mock *MockListFamilyGoalsInputPort
}

// NewMockListFamilyGoalsInputPort creates a new mock instance.
func NewMockListFamilyGoalsInputPort(ctrl *gomock.Controller) *MockListFamilyGoalsInputPort {
	mock := &MockListFamilyGoalsInputPort{ctrl: ctrl}
	mock.recorder = &MockListFamilyGoalsInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListFamilyGoalsInputPort) EXPECT() *MockListFamilyGoalsInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListFamilyGoalsInputPort) Execute(ctx context.Context, input usecase.ListFamilyGoalsInput) (*usecase.ListFamilyGoalsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.ListFamilyGoalsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListFamilyGoalsInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListFamilyGoalsInputPort)(nil).Execute), ctx, input)
}
