// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/list_tasks.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/list_tasks.go -destination=internal/usecase/mock/list_tasks.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockListTasksInputPort is a mock of ListTasksInputPort interface.
type MockListTasksInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockListTasksInputPortMockRecorder
	isgomock struct{}
}

// MockListTasksInputPortMockRecorder is the mock recorder for MockListTasksInputPort.
type MockListTasksInputPortMockRecorder struct {
	mock *MockListTasksInputPort
}

// NewMockListTasksInputPort creates a new mock instance.
func NewMockListTasksInputPort(ctrl *gomock.Controller) *MockListTasksInputPort {
	mock := &MockListTasksInputPort{ctrl: ctrl}
	mock.recorder = &MockListTasksInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListTasksInputPort) EXPECT() *MockListTasksInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListTasksInputPort) Execute(ctx context.Context, input usecase.ListTasksInput) (*usecase.ListTasksOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.ListTasksOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListTasksInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListTasksInputPort)(nil).Execute), ctx, input)
}
