// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/login_user.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/login_user.go -destination=internal/usecase/mock/login_user.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockLoginUserInputPort is a mock of LoginUserInputPort interface.
type MockLoginUserInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockLoginUserInputPortMockRecorder
	isgomock struct{}
}

// MockLoginUserInputPortMockRecorder is the mock recorder for MockLoginUserInputPort.
type MockLoginUserInputPortMockRecorder struct {
	mock *MockLoginUserInputPort
}

// NewMockLoginUserInputPort creates a new mock instance.
func NewMockLoginUserInputPort(ctrl *gomock.Controller) *MockLoginUserInputPort {
	mock := &MockLoginUserInputPort{ctrl: ctrl}
	mock.recorder = &MockLoginUserInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginUserInputPort) EXPECT() *MockLoginUserInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockLoginUserInputPort) Execute(ctx context.Context, input usecase.LoginUserInput) (*usecase.LoginUserOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.LoginUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockLoginUserInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockLoginUserInputPort)(nil).Execute), ctx, input)
}
