// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/logout_user.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/logout_user.go -destination=internal/usecase/mock/logout_user.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockLogoutUserInputPort is a mock of LogoutUserInputPort interface.
type MockLogoutUserInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockLogoutUserInputPortMockRecorder
	isgomock struct{}
}

// MockLogoutUserInputPortMockRecorder is the mock recorder for MockLogoutUserInputPort.
type MockLogoutUserInputPortMockRecorder struct {
	mock *MockLogoutUserInputPort
}

// NewMockLogoutUserInputPort creates a new mock instance.
func NewMockLogoutUserInputPort(ctrl *gomock.Controller) *MockLogoutUserInputPort {
	mock := &MockLogoutUserInputPort{ctrl: ctrl}
	mock.recorder = &MockLogoutUserInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogoutUserInputPort) EXPECT() *MockLogoutUserInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockLogoutUserInputPort) Execute(ctx context.Context, input usecase.LogoutUserInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockLogoutUserInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockLogoutUserInputPort)(nil).Execute), ctx, input)
}
