// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/refresh_access_token.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/refresh_access_token.go -destination=internal/usecase/mock/refresh_access_token.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockRefreshAccessTokenInputPort is a mock of RefreshAccessTokenInputPort interface.
type MockRefreshAccessTokenInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshAccessTokenInputPortMockRecorder
	isgomock struct{}
}

// MockRefreshAccessTokenInputPortMockRecorder is the mock recorder for MockRefreshAccessTokenInputPort.
type MockRefreshAccessTokenInputPortMockRecorder struct {
	mock *MockRefreshAccessTokenInputPort
}

// NewMockRefreshAccessTokenInputPort creates a new mock instance.
func NewMockRefreshAccessTokenInputPort(ctrl *gomock.Controller) *MockRefreshAccessTokenInputPort {
	mock := &MockRefreshAccessTokenInputPort{ctrl: ctrl}
	mock.recorder = &MockRefreshAccessTokenInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshAccessTokenInputPort) EXPECT() *MockRefreshAccessTokenInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRefreshAccessTokenInputPort) Execute(ctx context.Context, input usecase.RefreshAccessTokenInput) (*usecase.RefreshAccessTokenOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.RefreshAccessTokenOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockRefreshAccessTokenInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRefreshAccessTokenInputPort)(nil).Execute), ctx, input)
}
