// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/register_user.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/register_user.go -destination=internal/usecase/mock/register_user.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockRegisterUserInputPort is a mock of RegisterUserInputPort interface.
type MockRegisterUserInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockRegisterUserInputPortMockRecorder
	isgomock struct{}
}

// MockRegisterUserInputPortMockRecorder is the mock recorder for MockRegisterUserInputPort.
type MockRegisterUserInputPortMockRecorder struct {
	mock *MockRegisterUserInputPort
}

// NewMockRegisterUserInputPort creates a new mock instance.
func NewMockRegisterUserInputPort(ctrl *gomock.Controller) *MockRegisterUserInputPort {
	mock := &MockRegisterUserInputPort{ctrl: ctrl}
	mock.recorder = &MockRegisterUserInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegisterUserInputPort) EXPECT() *MockRegisterUserInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRegisterUserInputPort) Execute(ctx context.Context, input usecase.RegisterUserInput) (*usecase.RegisterUserOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.RegisterUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockRegisterUserInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRegisterUserInputPort)(nil).Execute), ctx, input)
}
