// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/send_appreciation.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/send_appreciation.go -destination=internal/usecase/mock/send_appreciation.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockSendAppreciationInputPort is a mock of SendAppreciationInputPort interface.
type MockSendAppreciationInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockSendAppreciationInputPortMockRecorder
	isgomock struct{}
}

// MockSendAppreciationInputPortMockRecorder is the mock recorder for MockSendAppreciationInputPort.
type MockSendAppreciationInputPortMockRecorder struct {
	mock *MockSendAppreciationInputPort
}

// NewMockSendAppreciationInputPort creates a new mock instance.
func NewMockSendAppreciationInputPort(ctrl *gomock.Controller) *MockSendAppreciationInputPort {
	mock := &MockSendAppreciationInputPort{ctrl: ctrl}
	mock.recorder = &MockSendAppreciationInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSendAppreciationInputPort) EXPECT() *MockSendAppreciationInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockSendAppreciationInputPort) Execute(ctx context.Context, input usecase.SendAppreciationInput) (*usecase.SendAppreciationOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.SendAppreciationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockSendAppreciationInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSendAppreciationInputPort)(nil).Execute), ctx, input)
}
