// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/token_helper.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/token_helper.go -destination=internal/usecase/mock/token_helper.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock
