// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/update_task.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/update_task.go -destination=internal/usecase/mock/update_task.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdateTaskInputPort is a mock of UpdateTaskInputPort interface.
type MockUpdateTaskInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateTaskInputPortMockRecorder
	isgomock struct{}
}

// MockUpdateTaskInputPortMockRecorder is the mock recorder for MockUpdateTaskInputPort.
type MockUpdateTaskInputPortMockRecorder struct {
	mock *MockUpdateTaskInputPort
}

// NewMockUpdateTaskInputPort creates a new mock instance.
func NewMockUpdateTaskInputPort(ctrl *gomock.Controller) *MockUpdateTaskInputPort {
	mock := &MockUpdateTaskInputPort{ctrl: ctrl}
	mock.recorder = &MockUpdateTaskInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateTaskInputPort) EXPECT() *MockUpdateTaskInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateTaskInputPort) Execute(ctx context.Context, input usecase.UpdateTaskInput) (*usecase.UpdateTaskOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.UpdateTaskOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateTaskInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateTaskInputPort)(nil).Execute), ctx, input)
}
