// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/update_recurrence_rule.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/update_recurrence_rule.go -destination=internal/usecase/mock/update_recurrence_rule.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdateRecurrenceRuleInputPort is a mock of UpdateRecurrenceRuleInputPort interface.
type MockUpdateRecurrenceRuleInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateRecurrenceRuleInputPortMockRecorder
	isgomock struct{}
}

// MockUpdateRecurrenceRuleInputPortMockRecorder is the mock recorder for MockUpdateRecurrenceRuleInputPort.
type MockUpdateRecurrenceRuleInputPortMockRecorder struct {
	mock *MockUpdateRecurrenceRuleInputPort
}

// NewMockUpdateRecurrenceRuleInputPort creates a new mock instance.
func NewMockUpdateRecurrenceRuleInputPort(ctrl *gomock.Controller) *MockUpdateRecurrenceRuleInputPort {
	mock := &MockUpdateRecurrenceRuleInputPort{ctrl: ctrl}
	mock.recorder = &MockUpdateRecurrenceRuleInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateRecurrenceRuleInputPort) EXPECT() *MockUpdateRecurrenceRuleInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateRecurrenceRuleInputPort) Execute(ctx context.Context, input usecase.UpdateRecurrenceRuleInput) (*usecase.UpdateRecurrenceRuleOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.UpdateRecurrenceRuleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateRecurrenceRuleInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateRecurrenceRuleInputPort)(nil).Execute), ctx, input)
}
