// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/update_profile.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/update_profile.go -destination=internal/usecase/mock/update_profile.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/enman/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdateProfileInputPort is a mock of UpdateProfileInputPort interface.
type MockUpdateProfileInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateProfileInputPortMockRecorder
	isgomock struct{}
}

// MockUpdateProfileInputPortMockRecorder is the mock recorder for MockUpdateProfileInputPort.
type MockUpdateProfileInputPortMockRecorder struct {
	mock *MockUpdateProfileInputPort
}

// NewMockUpdateProfileInputPort creates a new mock instance.
func NewMockUpdateProfileInputPort(ctrl *gomock.Controller) *MockUpdateProfileInputPort {
	mock := &MockUpdateProfileInputPort{ctrl: ctrl}
	mock.recorder = &MockUpdateProfileInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateProfileInputPort) EXPECT() *MockUpdateProfileInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateProfileInputPort) Execute(ctx context.Context, input usecase.UpdateProfileInput) (*usecase.UpdateProfileOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.UpdateProfileOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateProfileInputPortMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateProfileInputPort)(nil).Execute), ctx, input)
}
