// Code generated by handler_generator.go; DO NOT EDIT.
package handler

type Handler struct {
	DeleteAuthLogoutHandler
	GetFamiliesGoalsHandler
	GetFamilyTimelineHandler
	GetHealthHandler
	GetNotificationsHandler
	GetStatsContributionsHandler
	GetTaskTemplatesHandler
	GetTasksHandler
	GetUsersMeHandler
	PatchTasksDoneHandler
	PatchUsersMeHandler
	PostAuthLoginHandler
	PostAuthRefreshHandler
	PostAuthRegisterHandler
	PostFamiliesHandler
	PostFamiliesGoalsHandler
	PostFamiliesJoinHandler
	PostTasksHandler
	PostTasksAppreciationHandler
}