// Code generated by handler_generator.go; DO NOT EDIT.
package handler

type Handler struct {
	DeleteAuthLogoutHandler
	DeleteRecurrenceRuleHandler
	DeleteTaskHandler
	GetCalendarHandler
	GetFamiliesGoalsHandler
	GetFamilyTimelineHandler
	GetHealthHandler
	GetNotificationsHandler
	GetRecurrenceRulesHandler
	GetStatsContributionsHandler
	GetTaskTemplatesHandler
	GetTasksHandler
	GetUsersMeHandler
	PatchRecurrenceRulesHandler
	PatchTaskHandler
	PatchTasksDoneHandler
	PatchUsersMeHandler
	PostAuthLoginHandler
	PostAuthRefreshHandler
	PostAuthRegisterHandler
	PostFamiliesHandler
	PostFamiliesGoalsHandler
	PostFamiliesJoinHandler
	PostRecurrenceRulesHandler
	PostTasksHandler
	PostTasksAppreciationHandler
}