// Code generated by handler_generator.go; DO NOT EDIT.
package handler

type Handler struct {
	DeleteAuthLogoutHandler
	GetHealthHandler
	GetUsersMeHandler
	PatchUsersMeHandler
	PostAuthLoginHandler
	PostAuthRefreshHandler
	PostAuthRegisterHandler
	PostFamiliesHandler
	PostFamiliesJoinHandler
}