// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/appreciation_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/appreciation_repository.go -destination=internal/domain/repository/mock/appreciation_repository.go -package=repositorymock
//

// Package repositorymock is a generated GoMock package.
package repositorymock

import (
	context "context"
	reflect "reflect"

	model "github.com/daisuke-harada/enman/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAppreciationRepository is a mock of AppreciationRepository interface.
type MockAppreciationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAppreciationRepositoryMockRecorder
	isgomock struct{}
}

// MockAppreciationRepositoryMockRecorder is the mock recorder for MockAppreciationRepository.
type MockAppreciationRepositoryMockRecorder struct {
	mock *MockAppreciationRepository
}

// NewMockAppreciationRepository creates a new mock instance.
func NewMockAppreciationRepository(ctrl *gomock.Controller) *MockAppreciationRepository {
	mock := &MockAppreciationRepository{ctrl: ctrl}
	mock.recorder = &MockAppreciationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppreciationRepository) EXPECT() *MockAppreciationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAppreciationRepository) Create(ctx context.Context, appreciation *model.Appreciation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, appreciation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAppreciationRepositoryMockRecorder) Create(ctx, appreciation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAppreciationRepository)(nil).Create), ctx, appreciation)
}

// ExistsByTaskAndFromUser mocks base method.
func (m *MockAppreciationRepository) ExistsByTaskAndFromUser(ctx context.Context, taskID, fromUserID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByTaskAndFromUser", ctx, taskID, fromUserID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByTaskAndFromUser indicates an expected call of ExistsByTaskAndFromUser.
func (mr *MockAppreciationRepositoryMockRecorder) ExistsByTaskAndFromUser(ctx, taskID, fromUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByTaskAndFromUser", reflect.TypeOf((*MockAppreciationRepository)(nil).ExistsByTaskAndFromUser), ctx, taskID, fromUserID)
}

// FindByFamilyID mocks base method.
func (m *MockAppreciationRepository) FindByFamilyID(ctx context.Context, familyID uint) ([]*model.Appreciation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFamilyID", ctx, familyID)
	ret0, _ := ret[0].([]*model.Appreciation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFamilyID indicates an expected call of FindByFamilyID.
func (mr *MockAppreciationRepositoryMockRecorder) FindByFamilyID(ctx, familyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFamilyID", reflect.TypeOf((*MockAppreciationRepository)(nil).FindByFamilyID), ctx, familyID)
}

// FindByToUserID mocks base method.
func (m *MockAppreciationRepository) FindByToUserID(ctx context.Context, toUserID uint) ([]*model.Appreciation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByToUserID", ctx, toUserID)
	ret0, _ := ret[0].([]*model.Appreciation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByToUserID indicates an expected call of FindByToUserID.
func (mr *MockAppreciationRepositoryMockRecorder) FindByToUserID(ctx, toUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByToUserID", reflect.TypeOf((*MockAppreciationRepository)(nil).FindByToUserID), ctx, toUserID)
}
