// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/family_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/family_repository.go -destination=internal/domain/repository/mock/family_repository.go -package=repositorymock
//

// Package repositorymock is a generated GoMock package.
package repositorymock

import (
	context "context"
	reflect "reflect"

	model "github.com/daisuke-harada/enman/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockFamilyRepository is a mock of FamilyRepository interface.
type MockFamilyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFamilyRepositoryMockRecorder
	isgomock struct{}
}

// MockFamilyRepositoryMockRecorder is the mock recorder for MockFamilyRepository.
type MockFamilyRepositoryMockRecorder struct {
	mock *MockFamilyRepository
}

// NewMockFamilyRepository creates a new mock instance.
func NewMockFamilyRepository(ctrl *gomock.Controller) *MockFamilyRepository {
	mock := &MockFamilyRepository{ctrl: ctrl}
	mock.recorder = &MockFamilyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFamilyRepository) EXPECT() *MockFamilyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFamilyRepository) Create(ctx context.Context, family *model.Family) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, family)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFamilyRepositoryMockRecorder) Create(ctx, family any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFamilyRepository)(nil).Create), ctx, family)
}

// FindByInviteCode mocks base method.
func (m *MockFamilyRepository) FindByInviteCode(ctx context.Context, inviteCode string) (*model.Family, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByInviteCode", ctx, inviteCode)
	ret0, _ := ret[0].(*model.Family)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByInviteCode indicates an expected call of FindByInviteCode.
func (mr *MockFamilyRepositoryMockRecorder) FindByInviteCode(ctx, inviteCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByInviteCode", reflect.TypeOf((*MockFamilyRepository)(nil).FindByInviteCode), ctx, inviteCode)
}
