// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/family_goal_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/family_goal_repository.go -destination=internal/domain/repository/mock/family_goal_repository.go -package=repositorymock
//

// Package repositorymock is a generated GoMock package.
package repositorymock

import (
	context "context"
	reflect "reflect"

	model "github.com/daisuke-harada/enman/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockFamilyGoalRepository is a mock of FamilyGoalRepository interface.
type MockFamilyGoalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFamilyGoalRepositoryMockRecorder
	isgomock struct{}
}

// MockFamilyGoalRepositoryMockRecorder is the mock recorder for MockFamilyGoalRepository.
type MockFamilyGoalRepositoryMockRecorder struct {
	mock *MockFamilyGoalRepository
}

// NewMockFamilyGoalRepository creates a new mock instance.
func NewMockFamilyGoalRepository(ctrl *gomock.Controller) *MockFamilyGoalRepository {
	mock := &MockFamilyGoalRepository{ctrl: ctrl}
	mock.recorder = &MockFamilyGoalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFamilyGoalRepository) EXPECT() *MockFamilyGoalRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFamilyGoalRepository) Create(ctx context.Context, goal *model.FamilyGoal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, goal)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFamilyGoalRepositoryMockRecorder) Create(ctx, goal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFamilyGoalRepository)(nil).Create), ctx, goal)
}

// FindByFamilyID mocks base method.
func (m *MockFamilyGoalRepository) FindByFamilyID(ctx context.Context, familyID uint) ([]*model.FamilyGoal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFamilyID", ctx, familyID)
	ret0, _ := ret[0].([]*model.FamilyGoal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFamilyID indicates an expected call of FindByFamilyID.
func (mr *MockFamilyGoalRepositoryMockRecorder) FindByFamilyID(ctx, familyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFamilyID", reflect.TypeOf((*MockFamilyGoalRepository)(nil).FindByFamilyID), ctx, familyID)
}
