// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/recurrence_rule_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/recurrence_rule_repository.go -destination=internal/domain/repository/mock/recurrence_rule_repository.go -package=repositorymock
//

// Package repositorymock is a generated GoMock package.
package repositorymock

import (
	context "context"
	reflect "reflect"

	model "github.com/daisuke-harada/enman/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRecurrenceRuleRepository is a mock of RecurrenceRuleRepository interface.
type MockRecurrenceRuleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRecurrenceRuleRepositoryMockRecorder
	isgomock struct{}
}

// MockRecurrenceRuleRepositoryMockRecorder is the mock recorder for MockRecurrenceRuleRepository.
type MockRecurrenceRuleRepositoryMockRecorder struct {
	mock *MockRecurrenceRuleRepository
}

// NewMockRecurrenceRuleRepository creates a new mock instance.
func NewMockRecurrenceRuleRepository(ctrl *gomock.Controller) *MockRecurrenceRuleRepository {
	mock := &MockRecurrenceRuleRepository{ctrl: ctrl}
	mock.recorder = &MockRecurrenceRuleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecurrenceRuleRepository) EXPECT() *MockRecurrenceRuleRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRecurrenceRuleRepository) Create(ctx context.Context, rule *model.RecurrenceRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRecurrenceRuleRepositoryMockRecorder) Create(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRecurrenceRuleRepository)(nil).Create), ctx, rule)
}

// Delete mocks base method.
func (m *MockRecurrenceRuleRepository) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRecurrenceRuleRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRecurrenceRuleRepository)(nil).Delete), ctx, id)
}

// FindByFamilyID mocks base method.
func (m *MockRecurrenceRuleRepository) FindByFamilyID(ctx context.Context, familyID uint) ([]*model.RecurrenceRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFamilyID", ctx, familyID)
	ret0, _ := ret[0].([]*model.RecurrenceRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFamilyID indicates an expected call of FindByFamilyID.
func (mr *MockRecurrenceRuleRepositoryMockRecorder) FindByFamilyID(ctx, familyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFamilyID", reflect.TypeOf((*MockRecurrenceRuleRepository)(nil).FindByFamilyID), ctx, familyID)
}

// FindByID mocks base method.
func (m *MockRecurrenceRuleRepository) FindByID(ctx context.Context, id uint) (*model.RecurrenceRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.RecurrenceRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRecurrenceRuleRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRecurrenceRuleRepository)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockRecurrenceRuleRepository) Update(ctx context.Context, rule *model.RecurrenceRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRecurrenceRuleRepositoryMockRecorder) Update(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRecurrenceRuleRepository)(nil).Update), ctx, rule)
}
