// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/stats_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/stats_repository.go -destination=internal/domain/repository/mock/stats_repository.go -package=repositorymock
//

// Package repositorymock is a generated GoMock package.
package repositorymock

import (
	context "context"
	reflect "reflect"

	repository "github.com/daisuke-harada/enman/internal/domain/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockStatsRepository is a mock of StatsRepository interface.
type MockStatsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStatsRepositoryMockRecorder
	isgomock struct{}
}

// MockStatsRepositoryMockRecorder is the mock recorder for MockStatsRepository.
type MockStatsRepositoryMockRecorder struct {
	mock *MockStatsRepository
}

// NewMockStatsRepository creates a new mock instance.
func NewMockStatsRepository(ctrl *gomock.Controller) *MockStatsRepository {
	mock := &MockStatsRepository{ctrl: ctrl}
	mock.recorder = &MockStatsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsRepository) EXPECT() *MockStatsRepositoryMockRecorder {
	return m.recorder
}

// GetContributions mocks base method.
func (m *MockStatsRepository) GetContributions(ctx context.Context, familyID uint) ([]*repository.ContributionItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContributions", ctx, familyID)
	ret0, _ := ret[0].([]*repository.ContributionItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContributions indicates an expected call of GetContributions.
func (mr *MockStatsRepositoryMockRecorder) GetContributions(ctx, familyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContributions", reflect.TypeOf((*MockStatsRepository)(nil).GetContributions), ctx, familyID)
}
