//go:build ignore
// +build ignore

// auth_generator.go は api/resolved/openapi/openapi.yaml を解析し、
// Bearer JWT 認証が必要なルートの一覧を internal/interface/openapi/auth_routes.gen.go に生成します。
// このファイルは `go generate ./internal/interface/openapi` （make gen）で実行されます。
package main

import (
	"log"
	"os"
	"regexp"
	"sort"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

// openAPIPathRe は OpenAPI パスパラメータ `{param}` にマッチします。
var openAPIPathRe = regexp.MustCompile(`\{([^}]+)\}`)

// openAPIToEchoPath は OpenAPI 形式のパス（例: /api/v1/users/{id}）を
// Echo 形式（例: /api/v1/users/:id）に変換します。
func openAPIToEchoPath(p string) string {
	return openAPIPathRe.ReplaceAllString(p, ":$1")
}

// openAPISpec は openapi.yaml の最低限の構造を表します。
type openAPISpec struct {
	Paths map[string]map[string]openAPIOperation `yaml:"paths"`
}

// openAPIOperation は各 HTTP メソッドの操作を表します。
type openAPIOperation struct {
	Security []map[string][]string `yaml:"security"`
}

func hasBearerAuth(security []map[string][]string) bool {
	for _, s := range security {
		if _, ok := s["bearerAuth"]; ok {
			return true
		}
	}
	return false
}

// route は認証が必要な 1 ルートを表します。
type route struct {
	Method   string
	EchoPath string
}

const authRoutesTemplate = `// Code generated by auth_generator.go DO NOT EDIT.
// Source: api/resolved/openapi/openapi.yaml
// Run "make gen" to regenerate.
package openapi

// bearerAuthRoutes は Bearer JWT 認証が必要なルートの集合です。
// キー形式: "METHOD /echo/path/pattern"
var bearerAuthRoutes = map[string]struct{}{
{{- range .}}
	"{{.Method}} {{.EchoPath}}": {},
{{- end}}
}

// RequiresBearerAuth は指定の HTTP メソッドと Echo ルートパターンが
// Bearer JWT 認証を必要とするかどうかを返します。
// middleware.JWTAuthMiddleware から呼び出されます。
func RequiresBearerAuth(method, echoPath string) bool {
	_, ok := bearerAuthRoutes[method+" "+echoPath]
	return ok
}
`

func main() {
	// このジェネレータは internal/interface/openapi/ ディレクトリから
	// `go generate` 経由で実行されるため、パスはそこからの相対パスです。
	data, err := os.ReadFile("../../../../api/resolved/openapi/openapi.yaml")
	if err != nil {
		log.Fatalf("auth_generator: failed to read openapi.yaml: %v", err)
	}

	var spec openAPISpec
	if err := yaml.Unmarshal(data, &spec); err != nil {
		log.Fatalf("auth_generator: failed to parse openapi.yaml: %v", err)
	}

	httpMethods := []string{"get", "post", "put", "patch", "delete", "head", "options"}

	var routes []route
	for path, ops := range spec.Paths {
		echoPath := openAPIToEchoPath(path)
		for _, method := range httpMethods {
			op, ok := ops[method]
			if !ok {
				continue
			}
			if hasBearerAuth(op.Security) {
				routes = append(routes, route{
					Method:   strings.ToUpper(method),
					EchoPath: echoPath,
				})
			}
		}
	}

	// 生成結果を安定させるため、パス→メソッドの順でソートします。
	sort.Slice(routes, func(i, j int) bool {
		if routes[i].EchoPath != routes[j].EchoPath {
			return routes[i].EchoPath < routes[j].EchoPath
		}
		return routes[i].Method < routes[j].Method
	})

	tmpl := template.Must(template.New("auth_routes").Parse(authRoutesTemplate))

	f, err := os.Create("auth_routes.gen.go")
	if err != nil {
		log.Fatalf("auth_generator: failed to create auth_routes.gen.go: %v", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, routes); err != nil {
		log.Fatalf("auth_generator: failed to execute template: %v", err)
	}

	log.Printf("auth_generator: generated auth_routes.gen.go with %d protected routes", len(routes))
}
